name:   ipl_analytics
version: 1.0.0
config-version: 2

profile: ipl_databricks

model-paths: ["models"]
macro-paths: ["macros"]

models :
  ipl_analytics:
    staging:
      +materialized: view
      +catalog: ipl_catalog
      +schema: silver
    gold:
      +materialized: table
      +catalog: ipl_catalog
      +schema: gold
      +file_format: delta
